---
layout: cv
title: Tyler Carter's CV
---
# Tyler Carter
Student, Eagle Scout, Former Missionary.

<div id="webaddress">
<a href="https://www.linkedin.com/in/tyler-carter-b76994272/">Linkedin</a>
| <a href="https://www.facebook.com/tyler.carter.351104/">Facebook</a>
</div>


## Currently

Studying Acounting with a cluster in Data Science. 

### Specialized in

Customer Relations, both forms of passive and active descalation. 
Excel Manupilulation, by formulating cells and creating macros. 


### Research interests

Small Business Accounting, Contract Law, and Aquisations.


## Education

`Highschool Years`
__Huntingtown High__

`First Year College`
__Maryland Community College, Prince Frederick MD__

- Just Generals

`2019 - Current`
__BYUI, Rexburg ID__

- Major Accounting with a cluster in Data Science.



## Awards

`2015`
Eagle Scout, *Boy Scout of America*, Huntingtown, MD

Scholar Award, *Huntingtown High*, Huntingtown, MD

`2020-2024`
Numerous Employee of the Week, *Silverwood* It’s their version of the employee of the month.



## Projects

`I-Survive, An App`
An app made during the Hackathon I helped contribute with a team. This app connects survivors, life coaches, and friends in a group chat by matching by similarities.

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`2016-2018`
Served a mission for the Church of Jesus Chirst of Latter-day Saints in Riverside CA. I served in a variety of leadership opportunities over the course of the two years. From organizing church events, acting as an official representative of the Church, and filling out official reports on a weekly and monthly basis. 


## Occupation


`1.18 Years`
__Cashier__, My Giant


`6 Months`
__Cashier__, Dollar Tree

`4 Years`
__Guest Servicies__, Silverwood Themepark

`2 Years`
__Security Officer__, Silverwood Themepark / Scarywood



<!-- ### Footer

Last updated: May 2013 -->